image: docker:latest
services:
    - docker:dind

variables:
    DOCKER_DRIVER: overlay

stages:
    - build

build:
    stage: build
    script:
        - docker build -t "$CI_REGISTRY/corysanin/ffa-tycoon" .
        - if [ ! -z ${PROTECTEDBRANCH+x} ]; then docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY; docker push "$CI_REGISTRY/corysanin/ffa-tycoon"; fi