image: docker:latest
services:
    - docker:dind

variables:
    DOCKER_DRIVER: overlay

stages:
    - build

build:
    stage: build
    script:
        - docker build -t registry.gitlab.com/corysanin/ffa-tycoon .
        - if [ ! -z ${DOCKER_PASSWORD+x} ]; then echo "$DOCKER_PASSWORD" | docker login registry.gitlab.com -u "$DOCKER_USERNAME" --password-stdin; docker push "registry.gitlab.com/corysanin/ffa-tycoon"; fi