version: '2'

services:
   ffa-tycoon:
      container_name: ffa-tycoon
      build:
         context: ./
         dockerfile: ./Dockerfile
      ports:
         - 8080:8080
         - 8081:8081
      volumes:
         - ./storage:/usr/src/ffa-tycoon/storage
         - ./config:/usr/src/ffa-tycoon/config
         - ../ffa-tycoon-parks/parks:/usr/src/ffa-tycoon/parks
         - ../ffa-tycoon-parks/distribution:/usr/src/ffa-tycoon/maps:ro
      environment:
         TZ: America/Chicago
         TESTING: "yes"

   openrct2-dev:
      container_name: openrct2-for-ffatycoon-dev
      image: corysanin/openrct2-cli:develop-alpine
      restart: unless-stopped
      ports:
         - 11753:11753
         - 11754:11754/udp
      expose:
         - 35711
      volumes:
         - ./storage/server-01:/home/openrct2/.config/OpenRCT2
         - ./plugin/lib:/home/openrct2/.config/OpenRCT2/plugin/ffatycoon
         - ../openrct2-ffa-plugin-suite/lib:/home/openrct2/.config/OpenRCT2/plugin/pluginsuite
         - ../openrct2-remote-control/lib:/home/openrct2/.config/OpenRCT2/plugin/remote
         - ../ffa-tycoon-parks/object:/ffa-objects
      command:
         - "host"
         - "http://ffa-tycoon:8080/load/0"
   
   openrct2-release:
      container_name: openrct2-for-ffatycoon-release
      image: corysanin/openrct2-cli:latest-alpine
      restart: unless-stopped
      ports:
         - 11752:11752
      expose:
         - 35711
      volumes:
         - ./storage/server-02:/home/openrct2/.config/OpenRCT2
         - ./plugin/lib:/home/openrct2/.config/OpenRCT2/plugin/ffatycoon
         - ../openrct2-ffa-plugin-suite/lib:/home/openrct2/.config/OpenRCT2/plugin/pluginsuite
         - ../openrct2-remote-control/lib:/home/openrct2/.config/OpenRCT2/plugin/remote
         - ../ffa-tycoon-parks/object:/ffa-objects
      command:
         - "host"
         - "http://ffa-tycoon:8080/load/1"
   
   screenshotter:
      container_name: screenshotter-for-ffatycoon
      image: corysanin/rct-screenshotter
      volumes:
         - "~/.steam/steam/steamapps/common/Rollercoaster Tycoon 2:/rct2"
   
