version: '2'

services:
   ffa-tycoon:
      container_name: ffa-tycoon
      build:
         context: ./
         dockerfile: ./Dockerfile
      ports:
         - 8080:8080
         - 8081:8081
      volumes:
         - ./storage:/usr/src/ffa-tycoon/storage
         - ./config:/usr/src/ffa-tycoon/config
      environment:
         TZ: America/Chicago
         TESTING: "yes"

   openrct2-dev:
      container_name: openrct2-for-ffatycoon-dev
      image: corysanin/openrct2-cli:develop-ubuntu
      ports:
         - 35711:35711
         - 11753:11753
         - 11754:11754/udp
      expose:
         - 35711
      volumes:
         - ./storage/server-01:/home/openrct2/.config/OpenRCT2
      command:
         - "host"
         - "https://ffa-tycoon.com/parks/sandbox"
   
   openrct2-release:
      container_name: openrct2-for-ffatycoon-release
      image: corysanin/openrct2-cli:latest-ubuntu
      ports:
         - 35712:35711
         - 11754:11753
      expose:
         - 35711
      volumes:
         - ./storage/server-02:/home/openrct2/.config/OpenRCT2
      command:
         - "host"
         - "https://ffa-tycoon.com/parks/sandbox"
   
   screenshotter:
      container_name: screenshotter-for-ffatycoon
      image: corysanin/rct-screenshotter
      volumes:
         - "~/.steam/steam/steamapps/common/Rollercoaster Tycoon 2:/game"
   
